script:
  - make
addons:
  apt:
    packages:
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - dvipng
      - texlive-latex-recommended
      - biber
      - latexmk
